name: CD

on:
  workflow_dispatch:
    inputs:
      Environment:
        type: choice
        options:
        default: "DEV" 
        - DEV
        - PRO
    
permissions:
      id-token: write
      contents: read

env:
  ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
  ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
  ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"

jobs:

  cd:
    name: CD - Deploy App
    runs-on: ubuntu-latest

    steps:

      - name: Login via Azure Service Principal
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Set the target AKS cluster.
      - name: Set k8s context 
        uses: Azure/aks-set-context@v4
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          cluster-name: finlab-aks
          resource-group: rg-icasado-dvfinlab

      - name: Set AKS secrets
        uses: Azure/k8s-create-secret@v4
        with:
          container-registry-url: ${{ secrets.ACR_LOGIN_SERVER }}
          container-registry-username: ${{ secrets.ACR_USERNAME }}
          container-registry-password: ${{ secrets.ACR_PASSWORD }}
          secret-name: acr-secret
          
      - name: Deploy AKS
        uses: Azure/k8s-deploy@v5
        with:
          action: deploy
          manifests: |
              ./deployment.yaml
          images: |
              ${{ secrets.ACR_LOGIN_SERVER }}/final-project:${{ env.VERSION }}
          imagepullsecrets: |
              acr-secrets

