name: "Create Release Branch"

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version (e.g., 1.0.0)'
        required: true
        default: ''

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release Branch
        uses: icasado01/create-release/create-release/action.yaml@v1
        with:
          release_version: ${{ github.event.inputs.release_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
